# Generated by Django 3.2.8 on 2021-11-04 17:18

import api.models
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211025_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='document',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='documents', validators=[api.models.validate_file_extension]),
        ),
    ]
