# Generated by Django 3.2.8 on 2021-11-10 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20211105_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='barangay',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barbershop',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barbershop',
            name='postal_code',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barbershop',
            name='street',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='amenities', to='api.Amenities'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='appointments',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='api.Appointment'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='api.Comments'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='hours',
            field=models.ManyToManyField(blank=True, related_name='hours', to='api.OperationHours'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='messages', to='api.Message'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='api.Services'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='barbershop',
            field=models.ManyToManyField(blank=True, related_name='shops', to='api.Barbershop'),
        ),
    ]
